- src/main.rs
Fixes https://github.com/TheBevyFlock/bevy-template/issues/2.
> Disable console on Windows for release builds

- Cargo.toml
> Disable detailed logging

- .cargo/config_fast_builds.toml
- .gitignore
> Add fast config

- .github/workflows/release.yaml
Context: https://stackoverflow.com/questions/71944650/github-actions-workflow-environment-variable-values-dependent-on-environment
> Fix `release.yaml`

- .github/workflows/release.yaml
This is the one, I can feel it :clown_face:
> Fix `release.yaml` attempt #6

- src/main.rs
- web/index.html
- web/style.css
`style.css` will get some more content later (https://github.com/TheBevyFlock/bevy-template/issues/8).
> Fix web build

- src/core/dev.rs
- src/core/menu/mod.rs
- src/core/mod.rs
> Move transition logging to dev 

- src/core/asset.rs
- src/core/booting.rs
- src/core/camera.rs
- src/core/deflicker.rs
- src/core/dev.rs
- src/core/window.rs
- src/screen/credits.rs
- src/screen/mod.rs
- src/screen/playing.rs
- src/screen/title.rs
- src/util/mod.rs
- Changed visibility modifiers. This is not important for a game, but it makes unused code detection more accurate
- Added some comments
- Removed some comments that I thought didn't add much
- Chained `app.foo` calls
> Do some minor refactoring

- src/screen/credits.rs
- src/screen/title.rs
- src/util/ui/mod.rs
- src/util/ui/mouse_hover.rs
- src/util/ui/palette.rs
- src/util/ui/widgets.rs
> UI refactor

- .github/workflows/release.yaml
Release workflow had some warnings about deprecated stuff.
> Update actions in Github workflows

- src/game/movement.rs
Tested that it runs properly now.
> Fix `.single_mut()` panic

- src/core/booting.rs
- src/core/mod.rs
- src/game/mod.rs
- src/game/physics.rs
- src/game/spawn/level.rs
- src/game/spawn/mod.rs
- src/game/spawn/player.rs
- src/screen/mod.rs
- src/util/mod.rs
- src/util/ui/interaction.rs
- src/util/ui/mod.rs
- src/util/ui/palette.rs
- src/util/ui/widgets.rs
Fixes https://github.com/TheBevyFlock/bevy-template/issues/80.
This currently does not touch `pub(super)`.
> Replace `pub(crate)` with `pub`

- src/game/movement.rs
Related to https://github.com/TheBevyFlock/bevy-template/issues/92.
> Make player faster and apply facing

- src/game/movement.rs
- src/game/spawn/player.rs
- src/lib.rs
In relation to https://github.com/TheBevyFlock/bevy-template/issues/92.
> Wrap player around window edges

- src/screen/splash.rs
Fixes https://github.com/TheBevyFlock/bevy-template/issues/91.
There's no fade in for the title screen, so it kinda harshly snaps into existence.
> Add splash screen fade in/out animation

- src/game/movement.rs
- src/lib.rs
- src/screen/splash.rs
Fixes https://github.com/TheBevyFlock/bevy-template/issues/105.
> Rename `AppStep` -> `AppSet`

- src/game/assets.rs
- src/game/audio/sfx.rs
- src/game/audio/soundtrack.rs
- src/game/mod.rs
- src/game/spawn/player.rs
- src/screen/loading.rs
- src/screen/mod.rs
- src/screen/splash.rs
> Preload game assets

- README.md
- src/screen/credits.rs
- src/ui_tools/palette.rs
- src/ui_tools/widgets.rs
> Add asset credits in-game

- .github/workflows/release.yaml
May make https://github.com/TheBevyFlock/bevy-template/issues/40 easier, if their workflows are similar enough.
> Use matrix in release.yaml

- Trunk.toml
> Fix `Trunk.toml`

- Cargo.toml
Now that this PR was merged: https://github.com/bevyengine/bevy-website/pull/1553.
> Update optimization suggestions

- README-CI-CD.md
Related to https://github.com/TheBevyFlock/bevy_quickstart/issues/14.
> Add `README-CI-CD.md`

- README-TOOLS.md
Fixes https://github.com/TheBevyFlock/bevy-template/issues/53.
Related to https://github.com/TheBevyFlock/bevy-template/issues/14.
Will link to this from `README.md` once either PR gets merged.
> Add `README-TOOLS.md`

- Cargo.toml
See https://github.com/bevyengine/bevy/issues/14291
> Add optimization

- README.md
- docs/design.md
- src/ui/widgets.rs
> Write design doc

- docs/design.md
- src/game/assets.rs
- src/game/audio/sfx.rs
- src/game/audio/soundtrack.rs
- src/game/mod.rs
- src/game/spawn/player.rs
- src/screen/loading.rs
Fixes https://github.com/TheBevyFlock/bevy_quickstart/issues/168.
> Refactor some asset code

- src/lib.rs
- src/ui/widgets.rs
Improves some things that are not documented clearly enough that @christopherbiscardi discovered while using the template.
Resolves #171
> Improve documentation

- docs/tooling.md
Fixes https://github.com/TheBevyFlock/bevy_quickstart/issues/204.
> Recommend `tiny_bail` for error handling

- Cargo.lock
- Cargo.toml
Fixes https://github.com/TheBevyFlock/bevy_quickstart/issues/199.
Also took the opportunity to do `cargo update`.
> Disable tracing logs in release

- src/screens/credits.rs
- src/screens/title.rs
- src/ui/interaction.rs
- src/ui/mod.rs
> Remove InteractionQuery

- docs/design.md
- src/screens/credits.rs
- src/screens/loading.rs
- src/screens/playing.rs
- src/screens/title.rs
> Rename enter_* and exit_* systems

- src/ui/interaction.rs
> Add docs to InteractionPalette

- cargo-generate.toml
Fixes https://github.com/TheBevyFlock/bevy_quickstart/issues/197.
This should probably work.
> Include `index.html` in `cargo-generate.toml`

- src/game/animation.rs
- src/game/movement.rs
- src/game/spawn/player.rs
Part of https://github.com/TheBevyFlock/bevy_quickstart/issues/203
> Refactor and document `MovementController`

- README.md
> Fixed screens link

- docs/design.md
- src/assets.rs
- src/demo/animation.rs
- src/demo/player.rs
- src/screens/credits.rs
- src/screens/playing.rs
- src/theme/interaction.rs
This code should make it more clear that the asset key can be loaded from disk. 
I tried to limit my use of iterators in this PR because they tend to be complicated for beginners, but now there is a bit of a mix between procedural and iterator code. If you want, I can replace it all with procedural code.
Requesting a review from @alice-i-cecile as well.
> Be more data driven

- .vscode/extensions.json
Fixes https://github.com/TheBevyFlock/bevy_quickstart/issues/201.
> Add workspace recommended extensions for VS Code

- README.md
The README is useful even if you watch the video.
> Don't suggest not to read README in README

- README.md
- docs/design.md
- docs/workflows.md
Fixes https://github.com/TheBevyFlock/bevy_new_2d/issues/298.
> Recommend using `bevy new` instead of `cargo-generate`

- docs/design.md
Fixes https://github.com/TheBevyFlock/bevy_new_2d/issues/328.
> Remove mention of deleted `sickle_ui` repository

- Cargo.lock
- Cargo.toml
- Cargo.toml.template
- src/audio.rs
- src/audio.rs.template
- src/demo/level.rs
- src/demo/movement.rs
- src/demo/player.rs
- src/dev_tools.rs
- src/lib.rs
- src/screens/credits.rs
- src/screens/gameplay.rs
- src/screens/title.rs
- src/theme/widgets.rs
Fixes https://github.com/TheBevyFlock/bevy_new_2d/issues/334.
> Update to Bevy 0.16.0 release candidate

- .vscode/tasks.json
Fixes https://github.com/TheBevyFlock/bevy_new_2d/issues/329.
> Use `bevy run` for all VS Code tasks

- docs/design.md
- docs/tooling.md
- src/screens/credits.rs
- src/screens/title.rs
- src/theme/interaction.rs
- src/theme/mod.rs
> Replace `OnPress` component with `bevy_picking`

- src/screens/splash.rs
- src/theme/widgets.rs
Fixes https://github.com/TheBevyFlock/bevy_new_2d/issues/345.
> Prefer `children!` macro

- .github/workflows/release.yaml
- .github/workflows/release.yaml.template
- docs/workflows.md
Can't use `env` in `matrix` job definition, and can't use `env` in `if` either. Hoping this `forward-env` workaround is enough!
> Fix release workflow?

- .github/workflows/release.yaml
- .github/workflows/release.yaml.template
Tested this approach to toggling specific platforms in a separate repository, so it should work this time.
The duplication is pretty unfortunate, but the other workarounds I found mentioned in discussions (about not being able to use `matrix` in `jobs.<job-id>.if`) seemed more complicated.
> Fix release workflow for real

- .github/workflows/release.yaml
- .github/workflows/release.yaml.template
This was also broken by the migration to `bevy run`. The fix here is adding `--no-default-features`, but I figured I'd make the web workflow respect the `matrix` settings a bit more as well.
> Fix web release workflow

- .github/workflows/release.yaml
- .github/workflows/release.yaml.template
- .vscode/tasks.json
- Cargo.toml
- Cargo.toml.template
- README.md
This reverts commit d6fb38af7caae59194e77c76565e9d687b785ba4.
The bug is fixed: https://github.com/TheBevyFlock/bevy_cli/issues/370#event-17322161516
> Reapply "Add config to fix default web and release builds (#357)" (#358)

- src/lib.rs
- src/lib.rs.template
I couldn't reproduce the behavior the `IsDefaultUiCamera` comment was warning about, so I removed the comment and the component.
> Tidy up `lib.rs` a little bit

- src/demo/level.rs
- src/demo/mod.rs
- src/demo/player.rs
- src/screens/gameplay.rs
As part of this PR I also edited a few comments, mostly by deleting things I considered to be over-explaining or confusing. I'm open to opinions on those changes.
> Replace leftover command-based spawning API

- .github/workflows/ci.yaml
> Add Wasm build to CI

- README.md
Fixes https://github.com/TheBevyFlock/bevy_new_2d/issues/332.
We can add this section back later when there's a more up-to-date video.
> Remove link to video

- .github/workflows/release.yaml
- .github/workflows/release.yaml.template
I'll run a test release after this is merged.
> Use `bevy build` in native release workflow

- src/screens/settings.rs
I also made the volume label stay the same width whether it's 1, 2, or 3 digits long.
> Small style improvements for settings.rs

- docs/tooling.md
> Fix editing error in `tooling.md`
