.vscode/tasks.json

Fixes https://github.com/TheBevyFlock/bevy-template/issues/7.
We may need to update this file if we make changes to `Cargo.toml`. IMO whatever change we make, `cargo run` should still default to a native dev build. The args for a release build may change, though.

Add basic .vscode/tasks.json

---

.github/workflows/release.yaml
.vscode/tasks.json
Cargo.toml
src/main.rs

Fixes https://github.com/TheBevyFlock/bevy-template/issues/18.
`bevy/dynamic_linking` works for both web and native builds, so it goes in `dev`.

Add `dev` and `dev_native` features

---

Cargo.toml

Turns out it's not actually needed. I tested this on itch.io with my own template.
We'll still need to use `wasm-bindgen-cli` to build for web, but only as a CLI tool, not as a build dependency.

Remove `wasm-bindgen` dependency

---

Cargo.toml
src/main.rs

VS Code is autoformatting the `log = ...` line.

Move lints to `Cargo.toml` and add comments

---

src/screen/credits.rs
src/screen/title.rs
src/util/ui/interaction.rs
src/util/ui/mod.rs
src/util/ui/widgets.rs

Fixes https://github.com/TheBevyFlock/bevy-template/issues/64.
This also removes `ClearColor` and instead uses the `BackgroundColor` component of `ui_root`.

Refactor `util/ui/` and add prelude

---

src/screen/splash/mod.rs

If a user sets `DefaultPlugins.set(ImagePlugin::default_nearest())`, e.g. for a pixel art game, the splash screen image will look awful.
Explicitly specify a linear sampler for the splash screen image to guarantee that won't happen.

Make splash screen image explicitly linear

---

.github/workflows/release.yaml
Cargo.toml
web/index.html

Trunk only reads the `release` profile, see https://github.com/trunk-rs/trunk/issues/780
Also: trunk can already to `wasm-opt`, so no need to have a CI step for that.
I also switched from `cargo install` to `cargo binstall` to not spend 5 minutes compiling trunk

Fix Trunk builds

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

- Add `--all-targets`, which is short for `--lib --bins --tests --benches --examples`
- Add `cargo doc` checks. I have found that using `cargo doc` for development can be useful to read my own documentation and understand what the heck I was thinking a month ago. As such, it would be nice to check it in the CI. I pass `--no-deps` to not compile the dependencies in that step
- Implement #122
- Runs once for each macOS build
- Implement #118 
- Runs only once for macOS

Improve CI

---

.github/workflows/release.yaml

Note that this assumes that non-Mac / non-Web platforms will only have one target. If another target is added, there will be multiple binaries, and `mv` will try to move them to the same path which will error.

Rename binary in package

---

docs/design.md
src/game/animation.rs
src/game/assets.rs
src/game/audio/mod.rs
src/game/audio/sfx.rs
src/game/audio/soundtrack.rs
src/screen/credits.rs
src/screen/playing.rs
src/ui/interaction.rs

Overview of changes:
- Make some comments a bit more explicit.
- Derive `Copy, Clone` for asset keys.
- Add `sfx::plugin` and `soundtrack::plugin`.
- Rename marker component `SoundtrackMarker` -> `IsSoundtrack`.
- Rename events `Sfx` -> `PlaySfx` and `Soundtrack` -> `PlaySoundtrack`.
- Combine specific-key variants of `PlaySfx` and `PlaySoundtrack`.
- Simplify `play_sfx` and `play_soundtrack` function bodies (this might be controversial).
- Move `game::audio::sfx::button_interaction_sfx` -> `ui::interaction::trigger_interaction_sfx`.

Refactor audio a bit

---

README.md

No need to link trunk twice imo.
Also, I started explaining why this is the case and noticed that it got technical very quickly. I think it's fine.

Add info on release builds

---

docs/design.md

Fixes #189 by removing `bevy-design-patterns` and adding the cheatbook, which is nice to include anyways.

Replace broken link with actual resource

---

.github/workflows/release.yaml

Trunk automatically installs prerequisites, if they're not installed, when calling `trunk build --release`. It looks something like this when it occurs:
wasm-bindgen installs very quickly, but wasm-opt takes a non-trivial amount of time to install.
It is possible to install these dependencies using `cargo binstall` which can yield time savings.
On my own repository I had a build time of `4m 11s` prior to using `binstall wasm-opt` and a build time of `2m 40s` afterward.
Additionally, I had a build time of `2m 31s` after using `binstall wasm-bindgen-cli`, but I attribute some of this to variance because trunk installing wasm-bindgen only took 5 seconds in the above screenshot.
Nevertheless, it seems worthwhile to install `wasm-opt` via `cargo binstall` and I figured might as well install …

Use binstall to install wasm-bindgen and wasm-opt

---

.github/workflows/release.yaml
cargo-generate.toml

We now ask for the project name on itch.io if the user provides a username for itch.io. This is optional, and if left-blank we fallback to project-name.
I have to do this weirdly because I can't use template placeholders in `cargo-generate.toml` for defaults, as far as I could tell. We *could* create some hooks, but that is complicated and there are some issues we could run-into so I went this route instead so we wouldn't have to worry as much about it.
To elaborate on the issues with hooks, I'm specifically talking about `init` hooks. `init` *can* have access to `project-name` but it is not guaranteed. So we would have to babysit running order, which can be an issue. Additionally, I'm not completely certain on if they run after the prompt, before the prompt, or during the prompt. In …

Add in prompt for itch-project name.

---

src/screens/credits.rs
src/screens/title.rs
src/ui/interaction.rs
src/ui/mod.rs

Part of https://github.com/TheBevyFlock/bevy_quickstart/issues/203
Pattern taken from @Freyja-moth. Thanks Freyja!
Alternative to the following:
> `handle_title_action` should be done using observers, rather than a `TitleAction` component
[Relevant discussion](https://discord.com/channels/691052431525675048/1258521739395203174/1270111179494133840).  
The TL;DR is that registering a similar `OnPress<T: Event>(pub T)`, which would be need to trigger observers on presses, would require you to register your `T` in your menu in order to register the actual generic system for your `T`. Which seems like a weird extra abstraction to add and a potential source of errors, same a when a user forgets to do `add_event` for `EventReader`s and `EventWriter`s.
That, or you setup your logic for triggering …

Add `OnPress` callbacks

---

src/screens/credits.rs
src/screens/title.rs
src/ui/widgets.rs

Also implements #234 
Tried adding a closure directly to `fn button`, but that is rather cumbersome, as `ChildBuilder` does not have a `register_one_shot_system` method directly, which means we would have to re-implement it:
```rust
let entity = self.spawn_empty().id();
self.push(RegisterSystem::new(system, entity));
SystemId::from_entity(entity)
```
which is very very *meh*

Fix memory leak using one-shot systems

---

src/audio/soundtrack.rs
src/demo/level.rs
src/demo/player.rs
src/screens/playing.rs

Part of #203
Alternative to #231
Does *not* help with #223.

Use custom commands instead of observers for spawning

---

docs/design.md
src/screens/credits.rs
src/screens/title.rs
src/theme/interaction.rs
src/theme/widgets.rs

- This variant is probably closer to what will be upstreamed in Bevy, as Alice mentioned wanting to solve this using observers.
- Its implementation is simpler (no need to learn about one-shot systems or `SystemId`, no need to be careful about memory leaks)
- I removed the extra param from `button`. 
- With the current code, the user does not save on boilerplate when passing the callback to the function. But it incurs a bit of mental indirection that is not present when `observe` is called directly and it requires us to add some ugly generics to the `button` function. I like about the current code that it kinda teaches the user how to apply observers to entities for themselves.
- Of course, this means a user can forget to handle the `OnPress` event as a consequence.

Use observers for callbacks

---

.vscode/bevy.code-snippets

Fixes https://github.com/TheBevyFlock/bevy_quickstart/issues/202.

Add VS Code snippets for Bevy

---

README.md
src/dev_tools.rs

Fixes https://github.com/TheBevyFlock/bevy_quickstart/issues/211.
Toggle key is backtick, aka `KeyCode::Backquote`.

Add debug UI toggle

---

.github/workflows/release.yaml

Itch.io is migrating off the `itch.ovh` CDN domain, to `itch.zone`. They are recommending to use the new domain for downloading butler, see <https://github.com/itchio/butler/issues/257#issuecomment-1832707482>. It's unclear how long `itch.ovh` will remain available.
Fixes #255

Use the new `itch.zone` CDN domain for downloading butler

---

src/screens/loading.rs
src/theme/widgets.rs

Trivial fix for #220 
We can improve this further in future PRs, but this is at least better for the moment.

Fix label alignment

---

.editorconfig

This makes the indent size for YAML files in `.github/workflows` 2 spaces, as compared to 4. While YAML can technically support any indent size, all of the existing workflows in this repository already use 2 spaces. Furthermore, I had parsing issues in the past using 4 with Github Actions. (I'm unsure if it's a user-error on my part, or some specific of Github Actions.)

Make YAML indent size 2 in `.editorconfig`

---

src/screens/splash.rs

This PR allows the player to exit the splash screen at any time by hitting `KeyCode::escape`.
---
Previously this PR also contained code for displaying multiple splash screens, but after discussion that will be migrated to an example in the bevy repository.

Splash screen allows exiting early (with escape key)

---

src/demo/level.rs
src/screens/playing.rs

Simplify commands a bit

---

.github/workflows/cargo-generate.yaml

Closes #276.
This uses `gh` to query for open issues, counts them, then exits early if any exist.

Do not create a new issue on `cargo-generate` merge conflicts if one already exists

---

.gitignore

We're using `target/` for trunk's build artifacts, so this is no longer needed.

Remove `web/dist` from `.gitignore`

---

README.md

Currently links to
https://github.com/TheBevyFlock/bevy_quickstart/blob/main/src/screen/credits.rs
but should be
https://github.com/TheBevyFlock/bevy_quickstart/blob/main/src/screens/credits.rs

Fix tiny typo, `screen` -> `screens`

---

.github/workflows/cargo-generate.yaml

`cargo-generate.yaml` is an automated Github Action that automatically updates the `cargo-generate` branch from `main`. It's proven to be a bit flaky in the past, so I've found myself testing it on my fork a lot. The issue is that this action is automatically skipped if run on a fork. This is generally good, unless you want to test the workflow specifically and are not an average user.
The amend this, I made the action run if on the source repository OR if it was manually called using `workflow_dispatch`. This way, it won't run when `main` is updated on forks, but still will let developers manually call it if needed.

Allow running `cargo-generate` workflow on `workflow_dispatch` anywhere

---

src/asset_tracking.rs

`Vec::pop`/`Vec::push` touches only the last element of `Vec`. So, if the asset there failed to load, `load_resource_assets` wouldn't process remaining asset any more. This PR changes it to use `VecDeque::push_back`/`VecDeque::pop_front` instead.

Fix `load_resource` stops proceeding if any of asset loading failed

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

Fixes https://github.com/TheBevyFlock/bevy_quickstart/issues/291.
Trivial but not tested. Will do a test release after this is merged.

Add `--locked` to workflow cargo commands

---

README.md

Fixes https://github.com/TheBevyFlock/bevy_quickstart/issues/302.
Ideally the template would run `cargo update -p {{package-name}}` for the user in a post-generate script, but it's not clear if there's an easy way to run a CLI command from a Rhai script.

Update `cargo-generate` instructions

---

.github/workflows/release.yaml.template
Cargo.toml.template
cargo-generate.toml
post-generate.rhai
src/audio.rs.template
src/lib.rs.template
src/main.rs.template
web/index.html.template

Related to https://github.com/TheBevyFlock/bevy_quickstart/issues/288.
Testing:
- `cargo generate -ap path/to/bevy_quickstart` works
- `cargo run` in the generated repo works
- `cargo run` in the template itself works
Remaining tasks after this:

Fuse `cargo-generate` with `main` branch

---

Trunk.toml

With a brand new app and this template, I got an error running `trunk serve`. This seems to be due to the use of an IPv6 address which my version of Win10 doesn't seem to support.
```
ERROR error opening browser error=Custom { kind: Other, error: "Launcher "cmd" "/c" "start" "" "http://::1:8080/\" failed with ExitStatus(ExitStatus(1))" }
```
Adding the IPv4 address first in the `Trunk.toml` fixed this.
I'm not sure what impact this would have on other platforms?

Fix IPv6 Error on Win10 machine with trunk serve

---

src/asset_tracking.rs
src/screens/loading.rs

I wanted the ability to add new resources to the asset tracking system without having to explicitly add them to the list in screens::loading::all_assets_loaded each time. This change generalizes the system by using the data ResourceHandles already has about what has been loading and what's left.

Reduce boilerplate for adding additional loadable resources

---

Cargo.toml
Cargo.toml.template
clippy.toml

Fixes https://github.com/TheBevyFlock/bevy_new_2d/issues/326.
See the PR enabling this lint in Bevy itself: https://github.com/bevyengine/bevy/pull/17974.

Enable `nonstandard_macro_braces` lint

---

src/lib.rs.template

In https://github.com/TheBevyFlock/bevy_new_2d/pull/312 and https://github.com/TheBevyFlock/bevy_new_2d/pull/339, some changes were made to `lib.rs` but were forgotten to be copied over the `lib.rs.template`, resulting in broken projects.

Fix `lib.rs.template`

---

.github/workflows/release.yaml
.github/workflows/release.yaml.template
README.md
docs/tooling.md
docs/workflows.md

Fixes https://github.com/TheBevyFlock/bevy_new_2d/issues/212.
This adds some new flags to the release workflow:
- `use_github_cache` to toggle caching the release workflow, which is now _off_ by default because it unfortunately doesn't do anything unless the user releases multiple times _to the same tag_.
- `build_for_windows` etc. convenience toggles for individual platforms.
These changes can be tested (and fixed if necessary) after this PR is merged.

Improve CI usage awareness

---

.github/workflows/release.yaml
.github/workflows/release.yaml.template

This was actually broken by the migration to `bevy run`, not my changes :)

Fix cargo profiles in release workflow

---

docs/design.md
src/demo/player.rs
src/screens/credits.rs
src/screens/gameplay.rs
src/theme/interaction.rs

Fixes https://github.com/TheBevyFlock/bevy_new_2d/issues/284.
I believe the const `PATH_XYZ` were originally used as keys into a `HashMap`. The newer asset loading pattern uses named struct fields instead of a `HashMap`, so the consts are not needed anymore and can be removed.

Update asset loading docs (plus some cleanup)

---

README.md.template
cargo-generate.toml
post-generate.rhai

Specifically, ignore license files and documentation. A stub `README.md.template` has been added to point users to this repository for more information.

Add some files to `cargo-generate` ignore list

---

.github/workflows/release.yaml
.github/workflows/release.yaml.template
.vscode/tasks.json
Cargo.toml
Cargo.toml.template
README.md

We enable some dev features by default which do not work on Wasm, such as the `file-watcher`.
This causes the need to always add `--no-default-features` when running `bevy run web`.
Similarly, for release builds we also need to disable the dev features, also requiring `--no-default-features`.
Ideally, it should be possible to just use `bevy run web` and `bevy run --release` and having the features toggled automatically.
With <https://github.com/TheBevyFlock/bevy_cli/pull/331> we can define features or disable default features for dev/release and native/web builds.
This can be used to simplify the `web` and `release` commands.
- Install the latest version of Bevy CLI:
```
cargo install --git https://github.com/TheBevyFlock/bevy_cli --force --locked bevy_cli
```
- Use e.g. `bevy run web` …

Add config to fix default web and release builds

---

.github/workflows/release.yaml
.github/workflows/release.yaml.template
.vscode/tasks.json
Cargo.toml
Cargo.toml.template
README.md

This reverts commit dfbdbcbc3f373068d21f44e0cf73001462e8a019.
Otherwise, `bevy build` doesn't use the `dev_native` feature due to https://github.com/TheBevyFlock/bevy_cli/issues/370

Revert "Add config to fix default web and release builds (#357)"

---

docs/tooling.md

Since RustRover and other JetBrains IDEs don't allow us to easily share Live Templates (their version of the VSCode Snippets Functionality), I've included some basic information for those that *do* want to use that functionality, along with a very basic guide on how to port the existing vscode snippets to Live Templates.

Add in some documentation around Live Templates.

---

docs/design.md
src/screens/credits.rs
src/screens/loading.rs
src/screens/splash.rs
src/screens/title.rs
src/theme/widget.rs

This PR follows up on https://github.com/TheBevyFlock/bevy_new_2d/pull/366 by updating the design patterns documentation.
Summary of changes:
- Remove `Widgets` section
- Rename `Spawn Commands` -> `Bundle Functions` and update the contents of that section
- Reorder the sections in a more logical way
- Little edit pass on the `Screen States` section
- Add `name` argument to `fn ui_root()` for a more descriptive `Name` component

Reorder and update patterns doc

---

src/screens/credits.rs
src/screens/title.rs
src/theme/widget.rs

Using `Pointer<Released>` means that if a user presses down on empty space, then moves the cursor over a button and releases, the button's action will trigger. Instead, we should require the user to press down _on the button_ before releasing over the button, which is how `Pointer<Click>` behaves.

Trigger buttons on click, not on release

---

Cargo.lock
Cargo.toml
Cargo.toml.template

Set `bevy = "0.16"` and ran `cargo update`. Tested that it still compiles and runs.

Bump dependencies (Bevy 0.16)

---

src/audio.rs
src/audio.rs.template
src/demo/animation.rs
src/demo/movement.rs
src/lib.rs
src/lib.rs.template
src/screens/credits.rs
src/screens/gameplay.rs
src/theme/interaction.rs
src/theme/widget.rs

Please let me know if you don't like any of these changes, because they're subjective.
Summary of changes:
- Simplify comments in `audio.rs` and add bundle functions for sfx/music
- Split a `register_type::<(...)>` (see [cart's reasoning on Discord](https://discord.com/channels/691052431525675048/1002362493634629796/1351279139872571462))
- Use `Single` where possible (only one place)
- Use the `ChildSpawner` type alias instead of `RelatedSpawner<ChildOf>`
- Remove `I: Sync` trait bound by calling `IntoObserverSystem::into_system(action)` outside of the closure
I also looked for any cases where we could use Bevy's new error handling with `-> Result`, but we don't seem to have any good use cases for it.

Some style changes

---

src/screens/loading.rs
src/screens/mod.rs
src/screens/splash.rs
src/screens/title.rs

- This way, assets can load during the splash screen and title menu.
- Restarting the app will lead to visiting the loading state multiple times, but the UI will only show when actually loading anything
- We didn't preload the splash image before and are still not doing that because I'd prefer to [just use embedded_asset](https://github.com/bevyengine/bevy/issues/14246) once it works on all platforms

Move loading sync point to before gameplay

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
.github/workflows/release.yaml.template

From https://github.com/TheBevyFlock/bevy_new_2d/issues/377#issuecomment-2835276190:
> I think it may be worth switching to [`Swatinem/rust-cache`](https://github.com/Swatinem/rust-cache) instead. It's [used by the Rust project](https://github.com/search?q=repo%3Arust-lang%2Frust+%22Swatinem%2Frust-cache%22+language%3AYAML&type=code) and provides more features than `Leafwing-Studios/cargo-cache`. Its strategy of only caching dependencies, disabling incremental compilation, and cleaning files over a week old is likely better than what we're currently doing.
This PR is a test to see how `Swatinem/rust-cache` performs in CI, and whether it is better than `Leafwing-Studios/cargo-cache` in practice or not. Note that we can [make the cache only save when run on …

Switch to `Swatinem/rust-cache`

---

Cargo.toml

Otherwise, we might get this:
This error started cropping up in my 0.16 upgrades, dunno why. It happens on specific uses of `rand`, including through dependencies, so this might be very subtle for a user, especially since the error message is less then helpful.
Let's just remove that potential footgun :) I don't know how this interacts with the `RUSTFLAGS` env var that treats warnings as errors, but since we currently only run tests on native anyways, I figured it's alright.

Make web builds more robust

---

Cargo.toml

This improved Bevy-emitted warnings.
E.g.
gives some more debugging information:

Enable track_location

---

.vscode/tasks.json

We don't need any shell-specific features like glob, pipe, etc., we're just running a command with arguments, so we can use the simpler `"process"` task type.

Use `process` instead of `shell`

---

.github/workflows/release.yaml
.github/workflows/release.yaml.template

`bevy build --release` is not the same as `bevy build --profile release` currently. If we want Bevy CLI to pick up our release configuration, we need to explicitly pass `--release`, at which point we might as well remove the `--profile` argument at the cost of some workflow flexibility that we aren't using anyways.

Don't include dev features in release

---

.github/workflows/ci.yaml

The first cacheless run can often take longer than 30 mins according to reports on discord.
I also moved the env vars together :)
Note that I'm experimenting with using a single shared key for the cache in Foxtrot, I'll report back on how well that works.

Tweak workflow timeouts

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
.github/workflows/release.yaml.template

Passing `debuginfo=0` would reduce the cache size even further (order of ~200MB), but may remove some debug information we actually want in CI. To be on the safe side, this PR uses `debuginfo=1` which should still be a huge win.

Reduce workflow cache size

---

.github/workflows/ci.yaml

Context: https://github.com/TheBevyFlock/bevy_new_2d/pull/396#issuecomment-2863179476.
Also I just came across this relevant section in the GitHub Actions docs: [usage-limits-and-eviction-policy](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy).

Use `debuginfo=line-tables-only`

---

src/demo/level.rs
src/demo/mod.rs
src/screens/credits.rs
src/screens/gameplay.rs

Reasoning:
- The level can decide its own music
- The `LevelAssets` resource is useful in practice, as it will contain the level itself (in e.g. a `Handle<Scene>`) in a real project
- We remove an abstraction (the resource that holds an entity)
- fewer functions overall
- The `spawn_level` function looks less sad :)

Move level music to level

---

docs/tooling.md

I wanted to record `oxipng` and `gifski` somewhere relevant so I don't forget about them, and figured they could be useful to others as well.
Summary of changes:
- Added `oxipng` and `gifski` to `CLI tools`
- Added `inline_tweak` to `Libraries`
- Moved `Other templates` section to before IDE integration sections
- Added `# IDE integration` header
- Reworded some things a little bit

Update `tooling.md` a bit

---

.cargo/config_ci.toml
.github/workflows/ci.yaml

- Cache dynamic libraries
- Compile tests with fewer optimizations
- Disable [concurrent CI runs](https://stackoverflow.com/a/72408109/5903309) on the same branch, PR, or tag
- This should save computation on private repos

Optimize CI speed by a tiny bit

---

.github/workflows/release.yaml
.github/workflows/release.yaml.template
Cargo.lock
Cargo.toml
Cargo.toml.template

Also ran `cargo update`.
Tested this approach in `pyri_new_jam`.

Patch `getrandom` to a fork to fix `wasm_js` backend

---

Cargo.lock
Cargo.toml
Cargo.toml.template

The fix is not strictly needed until a user steps on a mine in the minefield and their web build breaks. Luckily we check the web build in CI so they'll notice that there is an issue, and the fix will be in their `Cargo.toml` ready to be uncommented.

Comment out the getrandom fix

---

.github/workflows/release.yaml
.github/workflows/release.yaml.template

Echoing into `GITHUB_ENV` does not make the environment variable available in the current shell context. It only becomes available in the following step.

Fix `RUSTFLAGS` in release workflow

---

.github/workflows/ci.yaml

In #445 a pinned `bevy_lint` version was used because the previous v0.3.0 version didn't support `let`-chains. Now that v0.4.0 is released, this is no longer necessary! (Plus, there have been several improvements to the action between the pinned commit and v0.4.0's release.)
I enabled the optional caching on `main` for the `bevy_lint` and `bevy_lint_driver` executables, which should speed up CI times at the miniscule cost of ~1.5 MB in cache for all 3 operating systems.
Definitely also check out the [release page for the list of changes](https://github.com/TheBevyFlock/bevy_cli/releases/tag/lint-v0.4.0)! There's been some cool progress since v0.3.0!

Run `bevy_lint` v0.4.0 in CI

---

.github/workflows/ci.yaml

See https://github.com/TheBevyFlock/bevy_new_2d/pull/445 and https://github.com/TheBevyFlock/bevy_new_2d/pull/451. If we went straight from v0.3 to v0.4 we would have simply bumped the version number and enabled caching in the `bevy_lint` installation action.

Revert obsolete changes to CI from `bevy_lint` updates

---

.cargo/config_fast_builds.toml

This updates our copy of `config_fast_builds.toml` to match that of [the engine's version](https://github.com/bevyengine/bevy/blob/3e12f310a42d5edf7dc10642359c1eed38b03094/.cargo/config_fast_builds.toml). Most of the diff is related to docs, but the biggest change is removing the LLD configuration for Linux, [as it's now enabled by default in Rust 1.90.0](https://blog.rust-lang.org/2025/09/01/rust-lld-on-1.90.0-stable/).

Update `config_fast_builds.toml` with upstream changes

---

Cargo.lock
Cargo.lock.template
Cargo.toml
Cargo.toml.template
README.md

Overview:
- Update bevy from `0.17.0-rc.0` to `0.17`.
- Run `cargo update`.
- Update hot patching instructions now that bevy has built-in support for it.

Update dependencies (bevy 0.17)

---

.github/workflows/release.yaml
.github/workflows/release.yaml.template

The upload to github releases job does not work currently due to the variable in the ´inputs' context being a boolean and not equal to ´true´. This changes the checks for both ´inputs.upload_to_github` and `inputs.deny_warnings`. Should fix https://github.com/TheBevyFlock/bevy_new_2d/issues/461#issue-3484755689

Fixed inputs context check against strings when they are booleans
